language: cpp
before_install:
  - sudo apt-get install -qq zlib1g-dev libgl1-mesa-swx11-dev libx11-dev libxext-dev libfreetype6-dev libopenal-dev freeglut3-dev
compiler:
  - clang
  - gcc
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
