language: cpp
before_install:
  - sudo yes | sudo add-apt-repository ppa:cubrid/cubrid
  - sudo apt-get install -qq zlib1g-dev libgl1-mesa-swx11-dev libx11-dev libxext-dev libfreetype6-dev libopenal-dev freeglut3-dev libxmu-dev libxi-dev libmsgpack-dev cxxtest
compiler:
  - clang
  - gcc
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./testsrunner
