# - Find ASIO

FIND_PATH(ASIO_INCLUDE_DIR NAMES asio.hpp)
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ASIO DEFAULT_MSG ASIO_INCLUDE_DIR)

IF(ASIO_FOUND)
  SET(ASIO_INCLUDE_DIRS ${ASIO_INCLUDE_DIR})
ELSE(ASIO_FOUND)
  SET(ASIO_INCLUDE_DIRS)
ENDIF(ASIO_FOUND)

MARK_AS_ADVANCED(ASIO_INCLUDE_DIR)
